### check server

GET http://127.0.0.1:5000/v1


###check register
POST http://127.0.0.1:5000/v1/auth/register
Content-Type: application/json

{
    "email": "admin15@gmail.com",
    "password": 123123123,
    "username": "hoang",
    "role": "CB-Phuong",
    "district": "1",
    "ward": "1"
}


###login

POST http://127.0.0.1:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123123123"
}

###logout
GET http://127.0.0.1:5000/api/v1/auth/logout
###user
GET http://127.0.0.1:5000/api/v1/users/659519f5ccce2036500c2bcd



